"""ConvoMem Python SDK — the official client library for the ConvoMem API."""

from convomem._async_client import AsyncConvoMemClient
from convomem._client import ConvoMemClient
from convomem._errors import (
    ConvoMemApiError,
    ConvoMemConfigError,
    ConvoMemError,
    ConvoMemTimeoutError,
)
from convomem._types import (
    BuyingSignal,
    CaptureRequest,
    CaptureResponse,
    ChannelBreakdown,
    Complaint,
    Conversation,
    ConversationEndRequest,
    ConversationEscalateRequest,
    ConversationListResponse,
    Customer,
    CustomerCreateRequest,
    CustomerListResponse,
    CustomerLookupParams,
    CustomerLookupResponse,
    CustomerUpdateRequest,
    EmbedTokenRequest,
    EmbedTokenResponse,
    Entity,
    EntityGraphEdge,
    EntityGraphNode,
    EntityGraphResponse,
    EntityListResponse,
    EntitySearchParams,
    FeedbackLookupRequest,
    FeedbackLookupResponse,
    FrequentIssue,
    HandoffParams,
    HandoffResponse,
    Insight,
    InsightActionRequest,
    InsightListResponse,
    InsightsDashboard,
    JourneyEntry,
    KeyMemory,
    Memory,
    MemoryAddRequest,
    MemoryContext,
    MemoryInAction,
    MemoryIngestRequest,
    MemoryListResponse,
    MemoryLookupParams,
    MemoryUpdateRequest,
    Message,
    OpenIssue,
    Org,
    OrgApiKey,
    OrgApiKeyCreateRequest,
    OrgAuditLog,
    OrgCreateRequest,
    OrgMember,
    OrgMemberAddRequest,
    OrgMemberUpdateRequest,
    OrgUpdateRequest,
    PipelineStats,
    SentimentPoint,
    SentimentTrend,
    Webhook,
    WebhookCreateRequest,
    WebhookUpdateRequest,
)

__all__ = [
    "AsyncConvoMemClient",
    # Insights
    "BuyingSignal",
    # Capture
    "CaptureRequest",
    "CaptureResponse",
    "ChannelBreakdown",
    "Complaint",
    # Conversations
    "Conversation",
    "ConversationEndRequest",
    "ConversationEscalateRequest",
    "ConversationListResponse",
    "ConvoMemApiError",
    # Clients
    "ConvoMemClient",
    "ConvoMemConfigError",
    # Errors
    "ConvoMemError",
    "ConvoMemTimeoutError",
    # Customers
    "Customer",
    "CustomerCreateRequest",
    "CustomerListResponse",
    "CustomerLookupParams",
    "CustomerLookupResponse",
    "CustomerUpdateRequest",
    # Embed
    "EmbedTokenRequest",
    "EmbedTokenResponse",
    # Entities
    "Entity",
    "EntityGraphEdge",
    "EntityGraphNode",
    "EntityGraphResponse",
    "EntityListResponse",
    "EntitySearchParams",
    "FeedbackLookupRequest",
    "FeedbackLookupResponse",
    "FrequentIssue",
    # Handoff
    "HandoffParams",
    "HandoffResponse",
    "Insight",
    "InsightActionRequest",
    "InsightListResponse",
    "InsightsDashboard",
    "JourneyEntry",
    "KeyMemory",
    # Memories
    "Memory",
    "MemoryAddRequest",
    "MemoryContext",
    "MemoryInAction",
    "MemoryIngestRequest",
    "MemoryListResponse",
    "MemoryLookupParams",
    "MemoryUpdateRequest",
    "Message",
    "OpenIssue",
    # Orgs
    "Org",
    "OrgApiKey",
    "OrgApiKeyCreateRequest",
    "OrgAuditLog",
    "OrgCreateRequest",
    "OrgMember",
    "OrgMemberAddRequest",
    "OrgMemberUpdateRequest",
    "OrgUpdateRequest",
    "PipelineStats",
    "SentimentPoint",
    "SentimentTrend",
    # Webhooks
    "Webhook",
    "WebhookCreateRequest",
    "WebhookUpdateRequest",
]

__version__ = "0.1.0"
